name: nowtur1 action

on:
  schedule:
    - cron: '07 */3 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowtur1 bot"

      - name: Download nowtur1.py from private repo
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          curl -s -H "Authorization: token $PRIVATE_REPO_TOKEN" \
               -H "Accept: application/vnd.github.v3.raw" \
               https://api.github.com/repos/absol12/restv/contents/py/nowtur1.py \
               -o nowtur1.py 

      - name: fetch content nowtur1
        run: |
          final_url=$(python3 nowtur1.py)
          echo "erstrm=${final_url}" >> $GITHUB_ENV
          dastrm=$(echo $final_url | sed 's/nowtv-live-ad.ercdn.net\/nowtv\/playlist.m3u8/nowtv.daioncdn.net\/nowtv\/nowtv.m3u8/')
          echo "dastrm=${dastrm}" >> $GITHUB_ENV

      - name: Clean up nowtur1.py
        run: rm -f nowtur1.py

      - name: Replace Text
        run: |
          erstrm=${erstrm}
          dastrm=${dastrm}
          sed -i "\|daioncdn.net/nowtv| c $dastrm" 01.m3u
          sed -i "\|ercdn.net/nowtv| c $erstrm" 01.m3u
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add 01.m3u
          git commit -m "nowtur1 updated"
          git push
